name: Build Dev Image

on:
  pull_request:
    branches: [dev]

jobs:
  build-and-push-dev:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (dev-latest)
        run: |
          docker build -t ghcr.io/${{ github.repository }}:dev-latest .
          docker push ghcr.io/${{ github.repository }}:dev-latest
